import time
print("")
print("")
print("K E R I S T O F E R")
print("")
print("")
t = input("Enter the target number ==>")
print("")
print("target = " + t)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("Connecting !")
time.sleep(0.7)
print("")
print("""

               { no hacked ❌️ }
                   { error : The server is down }


""")
